'use strict';
module.exports = [
    {
        "CHA_NAME": "Розница",
        "ACTIVE_STATUS": 1,
        "SAL_OWNER_PHONE": "77777777",
        "SAL_ACTIVE_FROM": "2016-09-21 00:00:00.0",
        "SAL_OWNER": null,
        "USE_NAME": "Демо",
        "SAL_NOTES": "Ориентир первой точки",
        "SAL_OWNER_IIN": null,
        "row": 1,
        "LOC_NAME": "Алматы",
        "SAL_ID": "SAL00000028",
        "BDN_NAME": "Алматы",
        "SAL_HOUSE": "Кабанбай батыра, 32",
        "SAL_OWNER_FIO": "",
        "SAL_CODE": 0,
        "SAL_ADDRESS": "Алматы, Кабанбай батыра, 32",
        "SAL_ACTIVE_TO": null,
        "PIM_NAME": null,
        "SAL_NETWORK_CLIENT": "0",
        "OWN_NAME": null,
        "SAL_NAME": "Демо ТТ №1",
        "SAL_OWNER_DATE": "2002-08-03 00:00:00.0",
        "STY_NAME": null
    },
    {
        "CHA_NAME": "Розница",
        "ACTIVE_STATUS": 1,
        "SAL_OWNER_PHONE": "77777777",
        "SAL_ACTIVE_FROM": "2016-09-21 00:00:00.0",
        "SAL_OWNER": null,
        "USE_NAME": "Демо",
        "SAL_NOTES": "Ориентир второй точки",
        "SAL_OWNER_IIN": null,
        "row": 1,
        "LOC_NAME": "Алматы",
        "SAL_ID": "SAL00000035",
        "BDN_NAME": "Алматы",
        "SAL_HOUSE": "Розыбакиева, 125",
        "SAL_OWNER_FIO": "",
        "SAL_CODE": 1,
        "SAL_ADDRESS": "Алматы, Розыбакиева, 125",
        "SAL_ACTIVE_TO": null,
        "PIM_NAME": null,
        "SAL_NETWORK_CLIENT": "0",
        "OWN_NAME": null,
        "SAL_NAME": "Демо ТТ №2",
        "SAL_OWNER_DATE": "2002-08-03 00:00:00.0",
        "STY_NAME": null
    },
    {
        "CHA_NAME": "КА",
        "ACTIVE_STATUS": 1,
        "SAL_OWNER_PHONE": "77777777",
        "SAL_ACTIVE_FROM": "2016-09-21 00:00:00.0",
        "SAL_OWNER": null,
        "USE_NAME": "Демо",
        "SAL_NOTES": "Ниже проспекта Аль-Фараби",
        "SAL_OWNER_IIN": null,
        "row": 1,
        "LOC_NAME": "Алматы",
        "SAL_ID": "SAL00000043",
        "BDN_NAME": "Алматы",
        "SAL_HOUSE": "Достык, 202",
        "SAL_OWNER_FIO": "",
        "SAL_CODE": 2,
        "SAL_ADDRESS": "Алматы, Достык, 202",
        "SAL_ACTIVE_TO": null,
        "PIM_NAME": null,
        "SAL_NETWORK_CLIENT": "0",
        "OWN_NAME": null,
        "SAL_NAME": "Демо ТТ №3",
        "SAL_OWNER_DATE": "2002-08-03 00:00:00.0",
        "STY_NAME": null
    }
]
